var sentences = {
  tagalog: {
    easy: [
      "Kumusta?",
      "Salamat!",
      "Munisipyo",
      "Eskwlehan",
      "Simbahan",
      "Hangin",
      "Kalayo",
      "Uran",
      "Tamsi",
      "Ayam",
      "Butiki",
      "Yatot"
    ], //easy
    medium: [
      "Maupay nga gab-i!",
      "Maupay nga adlaw!",
      "Ako maestra.",
      "Magsashower ako.",
      "Nanunuod ako tv.",
      "Mahal kita.",
      "Diin ka tikang?",
      "Wari ako sala.",
      "Maupay nga adlaw!",
      "Ano tim ngaran?"
    ], //med
    hard: [
      "Ako hi Pedro. Yana la ako kita haim ngadi ha bungto.",
      "Ako hi Juan. Ikaw, ano tim ngaran?",
      "An padi aadto ha simbahan nagmimisa.",
      "Makusog it hangin yana nga pati it mga dahon napapalid.",
      "An kalayo han kalan nabayaan nga nakasindi.",
      "Delikado na kumadto ha lawod yana nga gab-i.",
      "Unta diri kita maabutan hin uran kay waray kita payong."
    ]
  },

  english: {
    easy: [
      "hammer",
      "knife",
      "plane",
      "pliers",
      "saw",
      "scissors",
      "screwdriver",
      "vise",
      "wrench",
      "drill",
      "arm",
      "back",
      "ears",
      "eyes",
      "face",
      "feet",
      "fingers",
      "foot",
      "hair",
      "hands",
      "head",
      "knees",
      "legs",
      "mouth",
      "neck",
      "nose",
      "shoulders",
      "skin",
      "stomach",
      "teeth",
      "thumbs",
      "toes",
      "tongue",
      "tooth",
      "black",
      "blue",
      "brown",
      "gray",
      "green",
      "orange",
      "pink",
      "purple",
      "red",
      "white",
      "yellow",
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "one",
      "two",
      "three",
      "four",
      "five",
      "six",
      "seven",
      "eight",
      "nine",
      "ten",
      "attic",
      "basement",
      "bath tub",
      "bathroom",
      "bed",
      "bedroom",
      "blanket",
      "bookcase",
      "carpet",
      "ceiling",
      "chair",
      "closet",
      "couch",
      "curtain",
      "desk",
      "dining",
      "door",
      "fan",
      "floor",
      "furniture",
      "garage",
      "hall",
      "hallway",
      "key",
      "kitchen",
      "lamp",
      "lock",
      "mirror",
      "picture",
      "porch",
      "roof",
      "room",
      "rug",
      "shelf",
      "sink",
      "sofa",
      "stairs",
      "table",
      "toilet",
      "wall",
      "window",
      "airplane",
      "bicycle",
      "boat",
      "bus",
      "car",
      "helicopter",
      "horse",
      "jet",
      "motorcycle",
      "ship",
      "subway",
      "taxi",
      "train",
      "truck",
      "clear",
      "cloudy",
      "cold",
      "cool",
      "foggy",
      "hot",
      "humid",
      "rainy",
      "snowy",
      "stormy",
      "sunny",
      "warm",
      "windy",
      "belt",
      "boots",
      "cap",
      "coat",
      "dress",
      "gloves",
      "hat",
      "jacket",
      "jeans",
      "pajamas",
      "pants",
      "raincoat",
      "scarf",
      "shirt",
      "shoes",
      "skirt",
      "slacks",
      "slippers",
      "socks",
      "stockings",
      "suit",
      "sweater",
      "sweatshirt",
      "t-shirt",
      "tie",
      "trousers",
      "underclothes",
      "underpants",
      "undershirt",
      "alligator",
      "ant",
      "bear",
      "bee",
      "bird",
      "camel",
      "cat",
      "cheetah",
      "chicken",
      "chimpanzee",
      "cow",
      "crocodile",
      "deer",
      "dog",
      "dolphin",
      "duck",
      "eagle",
      "elephant",
      "fish",
      "fly",
      "fox",
      "frog",
      "giraffe",
      "goat",
      "goldfish",
      "hamster",
      "hippopotamus",
      "horse",
      "kangaroo",
      "kitten",
      "lion",
      "lobster",
      "monkey",
      "octopus",
      "owl",
      "panda",
      "pig",
      "puppy",
      "rabbit",
      "rat",
      "scorpion",
      "seal",
      "shark",
      "sheep",
      "snail",
      "snake",
      "spider",
      "squirrel",
      "tiger",
      "turtle",
      "wolf",
      "zebra",
      "aboard",
      "about",
      "above",
      "absent",
      "across",
      "after",
      "against",
      "along",
      "alongside",
      "amid",
      "amidst",
      "among",
      "around",
      "as",
      "at",
      "atop",
      "before",
      "behind",
      "below",
      "beneath",
      "beside",
      "between",
      "by",
      "despite",
      "during",
      "except",
      "excepting",
      "following",
      "for",
      "from",
      "in",
      "inside",
      "into",
      "like",
      "mid",
      "near",
      "next",
      "of",
      "off",
      "on",
      "opposite",
      "outside",
      "over",
      "past",
      "plus",
      "regarding",
      "round",
      "save",
      "since",
      "than",
      "through",
      "till",
      "times",
      "to",
      "toward",
      "towards",
      "under",
      "underneath",
      "until",
      "up",
      "upon",
      "with",
      "within",
      "without",
      "unt",
      "brother",
      "cousin",
      "daughter",
      "father",
      "granddaughter",
      "grandmother",
      "grandson",
      "mother",
      "nephew",
      "niece",
      "sister",
      "son",
      "stepdaughter",
      "stepmother",
      "stepson",
      "uncle",
      "bull",
      "calf",
      "cat",
      "chicken",
      "cow",
      "donkey",
      "duck",
      "goat",
      "goose",
      "hen",
      "horse",
      "lamb",
      "pig",
      "rooster",
      "sheep",
      "turkey",
      "aquatics",
      "archery",
      "athletics",
      "badminton",
      "baseball",
      "basketball",
      "boxing",
      "canoeing",
      "cycling",
      "equestrian",
      "fencing",
      "football",
      "gymnastics",
      "handball",
      "hockey",
      "judo",
      "rowing",
      "sailing",
      "shooting",
      "softball",
      "taekwondo",
      "tennis",
      "triathlon",
      "volleyball",
      "weightlifting"
    ],
    medium: [
      "Just go for it.",
      "Your Time is Now.",
      "Let your love out.",
      "Too clever is dumb",
      "Yes, No, Maybe So.",
      "We're all mad here.",
      "You live only once.",
      "Paint the town red.",
      "Ride like the wind.",
      "No feeling is final",
      "What's done is done.",
      "It's never too late.",
      "You are your choices.",
      "Follow your own star.",
      "Work hard stay humble",
      "Think outside the box.",
      "God doesn't make junk.",
      "What is normal anyway?",
      "Nobody cares about it.",
      "Don't worry, be happy.",
      "Think Less. Feel More.",
      "Thoughts rule the world",
      "Curiouser and curiouser!",
      "Tomorrow is another day.",
      "Dance lightly with life.",
      "Enjoy the little things.",
      "Faith can move mountains.",
      "Success and nothing less.",
      "Never doubt your instinct.",
      "Beginnings are always messy.",
      "Courage doesn't always roar.",
      "If you are good life is good.",
      "Ultimately love is everything",
      "Two rights don\'t equal a left.",
      "Happiness depends upon ourselves.",
      "Whatever happens, take responsibility",
      "Nobody can be uncheered with a balloon."
    ],
    hard: [
      "Fear of a name increases fear of the thing itself.",
      "Who in the world am I? Ah, that's the great puzzle.",
      "The more he gave away, the more delighted he became.",
      "Those who don\'t believe in magic will never find it.",
      "It does not do to dwell on dreams and forget to live.",
      "Today was good. Today was fun. Tomorrow is another one.",
      "\"You seemed so far away,\" Miss Honey whispered, awestruck.",
      "I think I can. I think I can. I think I can. I know I can.",
      "Imagination is the only weapon in the war against reality.",
      "\"I don't think -\"",
      "\"Then you shouldn't talk,\" said the Hatter.",
      "I\'ve heard tell that what you imagine sometimes comes true.",
      "Children are not so serious as grown-ups and love to laugh.",
      "Somewhere inside all of us is the power to change the world.",
      "Don't you know that everybody's got a Fairyland of their own?",
      "You have been my friend. That in itself is a tremendous thing.",
      "The things that make me different are the things that make me.",
      "A little nonsense now and then, is relished by the wisest men.",
      "\"We all can dance,\" he said, \"if we find the music that we love.\"",
      "You should never, never doubt something that no one is sure of.",
      "I am not afraid of storms, for I am learning how to sail my ship.",
      "If you don't know where you are going any road can take you there",
      "Alice:How long is forever? White Rabbit:Sometimes, just one second.",
      "How lucky I am to have something that makes saying goodbye so hard.",
      "\"Ah, music,\" he said, wiping his eyes. \"A magic beyond all we do here!\"",
      "It is most unlikely. But - here comes the big \"but\" - not impossible.",
      "It is when we are most lost that we sometimes find our truest friends.",
      "I'm afraid I can't explain myself, sir. Because I am not myself, you see?",
      "Having power is not nearly as important as what you choose to do with it.",
      "You sort of start thinking anything\'s possible if you\'ve got enough nerve.",
      "\"Anyone can ask questions,\" said Mr. Wonka. \"It\'s the answers that count.\"",
      "Sometimes, I\'ve believed as many as six impossible things before breakfast.",
      "It\'s no use going back to yesterday, because I was a different person then.",
      "I was walking along looking for somebody, and then suddenly I wasn\'t anymore.",
      "So many things are possible just as long as you don\'t know they\'re impossible.",
      "Sometimes, said Pooh, the smallest things take up the most room in your heart.",
      "A little consideration, a little thought for others, makes all the difference.",
      "Nothing is any fun if you can get as much of it as you want. Especially money."
     ]
  }
}

module.exports = sentences;
